
/* 
   Generic config.h file for GAI applets.
    
   You don't have to use it for your applet, but a few things will be simpler. 

   This file is autogenerated by the configure script.
   So don't add things you want permanent here.
*/
#ifndef GAI_CONFIG_H
#define GAI_CONFIG_H

#include <gai/gai.h>

#ifdef GAI_APPLET_DEFINES
static GaiApplet applet_defines = {
	    	"shermans_applet",
		"3.0.1",
		"Sherman's aquarium",
		"Jonas Aaberg, <cja@gmx.net> 2002-2005. Graphics by Jim Toomey.",
		"Program released under GNU GPL.\nMost graphics Copyrighted by Jim Toomey and is NOT under GNU GPL.",
		"Sherman's aquarium is an applet with the\ncreatures from Jim Toomey's\nwonderful comic, Sherman's Lagoon\n(www.slagoon.com).",
		"/usr/share/pixmaps/shermans_icon.png",
		"/usr/share/pixmaps/shermans"
};
#endif
#define LINUX
#define IMAGE_PATH "/usr/share/pixmaps/shermans"
#define APPLET_NAME "shermans_applet"
#define APPLET_VERSION "3.0.1"

#endif
