.TH SHERMANS-AQUARIUM "1" "March 2005" "shermans 3.0.1" "User Commands"
.SH NAME
shermans \- aquarium screensaver
.SH SYNOPSIS
.B sherman
[\fIoptions\fR]
.SH DESCRIPTION

This is a XscreenSaver "hack" that gives you an aquarium that takes
care of itself.  No feed, no cleaning and so on.

The fishes are done by Jim Toomey, the author of the "Sherman's
Lagoon" comics.  See /usr/share/doc/shermans-aquarium/copyright for
more information.

.SH OPTIONS

.TP
\fB\-sound\fR
Enable sound support
.TP
\fB\-soundprg\fR <command>
External command used to play sounds
.TP
\fB\-ogg\fR
Enable OGG support

.TP
\fB\-seafloor\fR
Show sea floor
.TP
\fB\-plants\fR #
Number of plants
.TP
\fB\-plantscale\fR #
Scale of plants
.TP
\fB\-bottomanimals\fR #
Number of bottom animals

.TP
\fB\-bg_solid\fR
Solid background color
.TP
\fB\-bg_shaded\fR
Shaded background
.TP
\fB\-bg_wateralike\fR
Water alike background
.TP
\fB\-bg_image\fR
Set user specified image as background
.TP
\fB\-bg_image_file\fR <image>
Set image to be used as background

.TP
\fB\-lcr\fR #
Lower color RGB red value
.TP
\fB\-lcg\fR #
Lower color RGB green value
.TP
\fB\-lcb\fR #
Lower color RGB blue value

.TP
\fB\-ucr\fR #
Upper color RGB red value
.TP
\fB\-ucg\fR #
Upper color RGB green value
.TP
\fB\-ucb\fR #
Upper color RGB blue value
	
.TP
\fB\-comics\fR
Show random Sherman's Lagoon comic strips
.TP
\fB\-comics_dir\fR <dir>
Set local directory to load comic strips from
.TP
\fB\-comics_delay\fR #
Set delay between comic strips

.TP
\fB\-random\fR
Random fish, population size given below
.TP
\fB\-selected\fR
User defined population
.TP
\fB\-random_pop\fR #
Population size

.PP
User defined population
.TP
\fB\-fish1\fR #
.TP
\fB\-fish2\fR #
.TP
\fB\-fish3\fR #
.TP
\fB\-fish4\fR #
.TP
\fB\-fish5\fR #
.TP
\fB\-fish6\fR #
.TP
\fB\-swordfish\fR #
.TP
\fB\-blowfish\fR #
.TP
\fB\-bdweller\fR #
.TP
\fB\-fillmore\fR #
.TP
\fB\-sherman\fR #
.TP
\fB\-megan\fR #
.TP
\fB\-hunter\fR #
.TP
\fB\-prey\fR #
.TP
\fB\-lori\fR #
.TP
\fB\-ernest\fR #
.TP
\fB\-squid\fR #
.TP
\fB\-hawthorne\fR #

.TP
\fB\-eat\fR
.TP
\fB\-explode\fR
.TP
\fB\-rebirth\fR
.TP
\fB\-scalediff\fR
.TP
\fB\-speed\fR #
.TP
\fB\-scale\fR #
.TP
\fB\-huntera\fR #
.TP
\fB\-sworda\fR #
.TP
\fB\-window-id\fR #
.TP
\fB\-root\fR
.TP
\fB\-bubble\fR #
.TP
\fB\-desktop\fR


.SH AUTHOR
\fBSherman's aquarium\fR was written by Jonas Aaberg.  See
/usr/share/doc/shermans-aquarium/AUTHORS for other contributors.
.PP
This manual page was written by Jose M. Moya <josem@debian.org>, for
the Debian  GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
/usr/share/doc/shermans-aquarium/*
